// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// row_euclidean_distance
NumericVector row_euclidean_distance(NumericMatrix X, NumericVector v);
RcppExport SEXP _pintervals_row_euclidean_distance(SEXP XSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(row_euclidean_distance(X, v));
    return rcpp_result_gen;
END_RCPP
}
// row_mahalanobis_distance
NumericVector row_mahalanobis_distance(NumericMatrix X, NumericVector v, NumericMatrix S_inv);
RcppExport SEXP _pintervals_row_mahalanobis_distance(SEXP XSEXP, SEXP vSEXP, SEXP S_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type S_inv(S_invSEXP);
    rcpp_result_gen = Rcpp::wrap(row_mahalanobis_distance(X, v, S_inv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pintervals_row_euclidean_distance", (DL_FUNC) &_pintervals_row_euclidean_distance, 2},
    {"_pintervals_row_mahalanobis_distance", (DL_FUNC) &_pintervals_row_mahalanobis_distance, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_pintervals(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
